Repository mkubdev/blender-cheatsheet, pull requests merged in 2022-10, with the labels that each got.

#1 fix: WebXDAO link
  README.md
Labels: invalid

#8 docs: add issue templates
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: documentation

#7 Added transform guide
  README.md
Labels: enhancement

#10 fix: readme links on the top
  README.md
Labels: bug

#12 FEAT: Add Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#11 FEAT: add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#13 docs: improve emojis and headers
  README.md
Labels: documentation
